#!/bin/sh
set -eu
src=/boot/firmware/tic80-wifi.nmconnection
if [ -f "$src" ]; then
    install -m 600 -o root -g root "$src" /etc/NetworkManager/system-connections/tic80-wifi.nmconnection
fi
/usr/sbin/rfkill unblock wifi
